### Data Wrangling: Join, Combine, and Reshape

In [1]:
import pandas as pd
import numpy as np

In [2]:
# combine Series into DataFrame

df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})

print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2

In [3]:
pd.merge(df1, df2) # merge by key (common columns), only common keys are merged

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [4]:
# If the column names are different in each object, you can specify them separately
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                    'data2': range(3)})

In [5]:
print(df3)
print(df4)

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6
  rkey  data2
0    a      0
1    b      1
2    d      2

In [6]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey') # By default merge does an 'inner' join; other options are 'left', 'right', 'outer'

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [7]:
pd.merge(df1, df2, how='outer') # The outer join takes the union of the keys

  key  data1  data2
0   a    2.0    0.0
1   a    4.0    0.0
2   a    5.0    0.0
3   b    0.0    1.0
4   b    1.0    1.0
5   b    6.0    1.0
6   c    3.0    NaN
7   d    NaN    2.0

![alt text](join.png "Title")

In [8]:
# concatenate
arr = np.arange(12).reshape((3, 4))

np.concat([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [9]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

pd.concat([s1, s2, s3]) # default axis=0

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [10]:
pd.concat([s1, s2, s3], axis=1)

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [11]:
s4 = pd.concat([s1, s3])
print(s4)
pd.concat([s1, s4], axis=1)

a    0
b    1
f    5
g    6
dtype: int64

     0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [12]:
pd.concat([s1, s4], axis=1, join='inner')

   0  1
a  0  0
b  1  1

In [13]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

pd.concat([df1, df2], ignore_index=True) # if index is not important

          a         b         c         d
0 -0.391964 -1.908617 -0.111450 -0.909060
1  1.429460  0.035872  0.108889 -0.330742
2 -0.467130 -0.652714 -0.726036 -0.352350
3 -0.526853 -1.013463       NaN  0.529899
4 -1.168535 -0.360669       NaN  0.308860

In [14]:
## Hierarchical Indexing enables you to have multiple index levels on an axis.

data = pd.Series(np.random.randn(9),
                 index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                        [1,2,3,1,3,1,2,2,3]])

print(data)

a  1   -1.266498
   2    2.352775
   3   -0.327371
b  1   -1.359866
   3   -0.804291
c  1    0.428615
   2    0.482931
d  2    0.146849
   3    0.068632
dtype: float64

In [15]:
# partial indexing
data['b':'c']

b  1   -1.359866
   3   -0.804291
c  1    0.428615
   2    0.482931
dtype: float64

In [16]:
data.unstack()

          1         2         3
a -1.266498  2.352775 -0.327371
b -1.359866       NaN -0.804291
c  0.428615  0.482931       NaN
d       NaN  0.146849  0.068632

In [17]:
data.unstack().stack()

a  1   -1.266498
   2    2.352775
   3   -0.327371
b  1   -1.359866
   3   -0.804291
c  1    0.428615
   2    0.482931
d  2    0.146849
   3    0.068632
dtype: float64

In [18]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(['Ohio', 'Colorado'], name='state'),
                    columns=pd.Index(['one', 'two', 'three'],
                                     name='number'))

In [19]:
print(data)
result = data.stack()
print(result)

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5
state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [20]:
result.unstack()

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [21]:
# Pivoting between "Long" to "Wide" Format
data = pd.read_csv('./macrodata.csv')

In [22]:
data.head()

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959,1,2710.349,1707.4,286.898,470.045,1886.9,28.98,139.7,2.82,5.8,177.146,0.00,0.00
1,1959,2,2778.801,1733.7,310.859,481.301,1919.7,29.15,141.7,3.08,5.1,177.830,2.34,0.74
2,1959,3,2775.488,1751.8,289.226,491.260,1916.4,29.35,140.5,3.82,5.3,178.657,2.74,1.09
3,1959,4,2785.204,1753.7,299.356,484.052,1931.3,29.37,140.0,4.33,5.6,179.386,0.27,4.06
4,1960,1,2847.699,1770.5,331.722,462.199,1955.5,29.54,139.6,3.50,5.2,180.007,2.31,1.19

In [23]:
periods = pd.PeriodIndex.from_fields(year=data.year, quarter=data.quarter, freq='Q') # create a period index
periods.name = 'date'
columns = pd.Index(['realgdp', 'infl', 'unemp'], name='item')
data = data.reindex(columns=columns)
data.index = periods.to_timestamp('D', 'end') # convert to timestamp, 'D' means day, 'end' means the end of the day
df_long = data.stack().reset_index().rename(columns={0: 'value'})

# print(df_long.head())
print(df_long)

                             date     item      value
0   1959-03-31 23:59:59.999999999  realgdp   2710.349
1   1959-03-31 23:59:59.999999999     infl      0.000
2   1959-03-31 23:59:59.999999999    unemp      5.800
3   1959-06-30 23:59:59.999999999  realgdp   2778.801
4   1959-06-30 23:59:59.999999999     infl      2.340
..                            ...      ...        ...
604 2009-06-30 23:59:59.999999999     infl      3.370
605 2009-06-30 23:59:59.999999999    unemp      9.200
606 2009-09-30 23:59:59.999999999  realgdp  12990.341
607 2009-09-30 23:59:59.999999999     infl      3.560
608 2009-09-30 23:59:59.999999999    unemp      9.600

[609 rows x 3 columns]

In [24]:
# Data is frequently stored this way in relational databases like MySQL
pivoted = df_long.pivot(index='date', columns='item', values='value')
print(pivoted.head())

item                           infl   realgdp  unemp
date
1959-03-31 23:59:59.999999999  0.00  2710.349    5.8
1959-06-30 23:59:59.999999999  2.34  2778.801    5.1
1959-09-30 23:59:59.999999999  2.74  2775.488    5.3
1959-12-31 23:59:59.999999999  0.27  2785.204    5.6
1960-03-31 23:59:59.999999999  2.31  2847.699    5.2

In [25]:
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],
                   'A': [1, 2, 3],
                   'B': [4, 5, 6],
                   'C': [7, 8, 9]})

df

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [26]:
melted = pd.melt(df, ['key']) # melt is the inverse of pivot
melted

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [27]:
reshaped = melted.pivot(index='key', columns='variable', values='value')
print(reshaped)

variable  A  B  C
key
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [28]:
reshaped.reset_index() # Since the pivot result has a hierarchical index, using reset_index will turn the data back into a regular DataFrame

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

### Q1
Solve the following questions based on the given dataframe

1. Standardize the 'product' column by converting all values to lowercase
2. Replace the -999 value in the 'quantity' column with NaN
3. Remove any duplicate rows based on the 'product' and 'price' columns
4. Calculate the average price per product type

In [29]:
data = pd.DataFrame({
    'product': ['Apple', 'Banana', 'Orange', 'apple', 'BANANA', 'orange', 'Apple'],
    'price': [1.5, 0.5, 0.8, 1.2, 0.5, 0.8, 1.2],
    'quantity': [10, 20, 15, 5, -999, 18, 8],
    'store': ['A', 'B', 'A', 'C', 'B', 'C', 'A']
})
data

  product  price  quantity store
0   Apple    1.5        10     A
1  Banana    0.5        20     B
2  Orange    0.8        15     A
3   apple    1.2         5     C
4  BANANA    0.5      -999     B
5  orange    0.8        18     C
6   Apple    1.2         8     A

In [30]:
# 1. 
data['product'] = data['product'].str.lower()

# 2. a
data['quantity'] = data['quantity'].replace(-999, np.nan)

# 3. 
data = data.drop_duplicates(subset=['product', 'price'])

print(data)

  product  price  quantity store
0   apple    1.5      10.0     A
1  banana    0.5      20.0     B
2  orange    0.8      15.0     A
3   apple    1.2       5.0     C

In [31]:
# 4.
average_price = data.groupby('product')['price'].mean()
print(average_price)

product
apple     1.35
banana    0.50
orange    0.80
Name: price, dtype: float64