Read the Estuary_fish.csv file
• save samples with:
• management == Protected, Shore == Healthy and length > 2.0
• to a new file

In [12]:
import pandas as pd

# Read the CSV file
df = pd.read_csv("Estuary_fish.csv")
df

   Management      Shore  Length
0   Protected    Healthy    10.4
1   Protected    Healthy     2.0
2   Protected    Healthy     3.0
3   Protected    Healthy     7.3
4   Protected    Healthy     9.2
..        ...        ...     ...
75  Protected  Urbanised     3.8
76  Protected  Urbanised    11.4
77  Protected  Urbanised     4.0
78  Protected  Urbanised     6.9
79  Protected  Urbanised     5.1

[80 rows x 3 columns]

In [15]:
# Filter samples based on the given conditions
filtered_df = df[(df['Management'] == 'Protected') & 
                 (df['Shore'] == 'Healthy') & 
                 (df['Length'] > 2.0)]
filtered_df

# The system is sensitive to uppercase letters

   Management    Shore  Length
0   Protected  Healthy    10.4
2   Protected  Healthy     3.0
3   Protected  Healthy     7.3
4   Protected  Healthy     9.2
5   Protected  Healthy     2.9
6   Protected  Healthy     8.4
7   Protected  Healthy     2.7
8   Protected  Healthy    10.5
9   Protected  Healthy     8.2
31  Protected  Healthy     3.5
32  Protected  Healthy     9.0
33  Protected  Healthy     2.7
34  Protected  Healthy    13.1
35  Protected  Healthy     8.9
36  Protected  Healthy     4.9
37  Protected  Healthy     3.1
38  Protected  Healthy     4.0
39  Protected  Healthy    17.1

In [11]:
# Save the filtered data to a new CSV file
filtered_file_path = "Filtered_Estuary_fish.csv"
filtered_df.to_csv(filtered_file_path, index=False)

print(f"Filtered data saved to '{filtered_file_path}'.")

Filtered data saved to 'Filtered_Estuary_fish.csv'.